import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateDbStructure1741703283991 implements MigrationInterface {
    name = 'UpdateDbStructure1741703283991'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "url" character varying NOT NULL, "file_type" character varying NOT NULL, "file_name" character varying NOT NULL, "metadata" jsonb, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assets_whitelist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asset_id" character varying NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "vaultId" uuid, CONSTRAINT "PK_85cf89e7248c7f3f4013e524c84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "name" character varying NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "vaultId" uuid, CONSTRAINT "PK_ecf17f4a741d3c5ba0b4c5ab4b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "bannerUrl"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "socialLinks"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "valuation_type" "public"."vaults_valuation_type_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "contribution_open_window_type" "public"."vaults_contribution_open_window_type_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "contribution_open_window_time" character varying`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "asset_window" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "asset_count_cap_min" integer`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "asset_count_cap_max" integer`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "investment_window_duration" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "investment_open_window_type" "public"."vaults_investment_open_window_type_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "investment_open_window_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "off_assets_offered" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ft_investment_window" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ft_investment_reverse" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "liquidity_pool_contribution" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ft_token_supply" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ft_token_decimals" smallint DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "termination_type" "public"."vaults_termination_type_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "time_elapsed_is_equal_to_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "asset_appreciation" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "creation_threshold" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "start_threshold" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "vote_threshold" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "execution_threshold" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "cosigning_threshold" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "vault_status" "public"."vaults_vault_status_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "vaultImageId" uuid`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "UQ_2abd376a23e75271cb52cebbd98" UNIQUE ("vaultImageId")`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "bannerImageId" uuid`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "UQ_7c28507516704086b715221fdb5" UNIQUE ("bannerImageId")`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "whitelistCsvId" uuid`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "UQ_b34dd646f53a04849690f924867" UNIQUE ("whitelistCsvId")`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ftTokenImgId" uuid`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "UQ_e0aa86e723360729933673c514e" UNIQUE ("ftTokenImgId")`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "FK_2595182ac08342bf379e1b68657"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "PK_487a5346fa3693a430b6d6db60c"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "PK_487a5346fa3693a430b6d6db60c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "type" "public"."vaults_type_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "privacy"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "privacy" "public"."vaults_privacy_enum"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ownerId" uuid`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "CHK_9d2496e0bc2b30a41372df4bd4" CHECK ("ft_token_decimals" BETWEEN 1 AND 9)`);
        await queryRunner.query(`ALTER TABLE "assets_whitelist" ADD CONSTRAINT "FK_f985e605f0163582ba9add0540f" FOREIGN KEY ("vaultId") REFERENCES "vaults"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "links" ADD CONSTRAINT "FK_145012215d1a97515045abe0c8f" FOREIGN KEY ("vaultId") REFERENCES "vaults"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "FK_2595182ac08342bf379e1b68657" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "FK_2abd376a23e75271cb52cebbd98" FOREIGN KEY ("vaultImageId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "FK_7c28507516704086b715221fdb5" FOREIGN KEY ("bannerImageId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "FK_b34dd646f53a04849690f924867" FOREIGN KEY ("whitelistCsvId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "FK_e0aa86e723360729933673c514e" FOREIGN KEY ("ftTokenImgId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "FK_e0aa86e723360729933673c514e"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "FK_b34dd646f53a04849690f924867"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "FK_7c28507516704086b715221fdb5"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "FK_2abd376a23e75271cb52cebbd98"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "FK_2595182ac08342bf379e1b68657"`);
        await queryRunner.query(`ALTER TABLE "links" DROP CONSTRAINT "FK_145012215d1a97515045abe0c8f"`);
        await queryRunner.query(`ALTER TABLE "assets_whitelist" DROP CONSTRAINT "FK_f985e605f0163582ba9add0540f"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "CHK_9d2496e0bc2b30a41372df4bd4"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "ownerId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "privacy"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "privacy" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "PK_487a5346fa3693a430b6d6db60c"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "PK_487a5346fa3693a430b6d6db60c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD CONSTRAINT "FK_2595182ac08342bf379e1b68657" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "UQ_e0aa86e723360729933673c514e"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ftTokenImgId"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "UQ_b34dd646f53a04849690f924867"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "whitelistCsvId"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "UQ_7c28507516704086b715221fdb5"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "bannerImageId"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP CONSTRAINT "UQ_2abd376a23e75271cb52cebbd98"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "vaultImageId"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "vault_status"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "cosigning_threshold"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "execution_threshold"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "vote_threshold"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "start_threshold"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "creation_threshold"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "asset_appreciation"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "time_elapsed_is_equal_to_time"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "termination_type"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ft_token_decimals"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ft_token_supply"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "liquidity_pool_contribution"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ft_investment_reverse"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "ft_investment_window"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "off_assets_offered"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "investment_open_window_time"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "investment_open_window_type"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "investment_window_duration"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "asset_count_cap_max"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "asset_count_cap_min"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "asset_window"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "contribution_open_window_time"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "contribution_open_window_type"`);
        await queryRunner.query(`ALTER TABLE "vaults" DROP COLUMN "valuation_type"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "socialLinks" jsonb`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "bannerUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "vaults" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP TABLE "links"`);
        await queryRunner.query(`DROP TABLE "assets_whitelist"`);
        await queryRunner.query(`DROP TABLE "files"`);
    }

}
