import { VaultCreationSpec } from './spec.types';

import { ChainType } from '@/types/vault.types';

const DAY_MS = 86_400_000;

export const VAULT_TAGS = [
  'NFT',
  'FT',
  'RWA',
  'Real Estate',
  'Insurance',
  'Commodity',
  'Synthetic',
  'Exotic',
  'Precious Metal',
  'Gem',
  'DeFi',
  'PFP',
  'Staking',
  'DePin',
  'Stablecoin',
  'Memecoins',
  'Governance',
  'DEX',
  'Gaming',
  'Music',
  'Art',
  'Metaverse',
  'Utility',
  'Collectible',
  'Protocol',
  'LP Token',
  'Wrapped',
] as const;

/**
 * Single source of truth for what the AI assistant is allowed to propose when creating a vault.
 *
 * Mirrors `l4va-client/src/components/vaults/constants/vaults.constants.js` (yup `vaultSchema`)
 * and `CreateVaultReq` — update this file in the same PR that changes either validator.
 * Drift is not fatal: the client re-validates every AI draft against the live yup schema and
 * feeds the errors back for correction, so a stale spec costs an extra turn, not a bad vault.
 */
export const VAULT_CREATION_SPEC: VaultCreationSpec = {
  version: '1.3.0',

  rules: [
    'Percentages are whole-number percents (0-100), not basis points.',
    'All durations are in milliseconds.',
    'liquidityPoolContribution must be 0 when tokensForAcquires is 0.',
    'Set tokensForAcquires to 0 for a contribution-only vault; the acquire window is then skipped.',
    'isAcquireOnly vaults skip asset contribution entirely and always use tokensForAcquires = 100.',
    'valueMethod may only be "fixed" for private vaults; every other privacy setting must use "lbe".',
    'terminationType is always "dao" — "programmed" is not available yet.',
    'Never invent wallet addresses, policy IDs, contract addresses, social links or image URLs.',
  ],

  fields: {
    // --- Step 1: Configure ---------------------------------------------------
    name: {
      type: 'string',
      step: 1,
      required: true,
      minLength: 3,
      maxLength: 50,
      description: 'Public vault name.',
      aiEditable: true,
    },
    type: {
      type: 'enum',
      step: 1,
      required: true,
      values: ['single', 'multi', 'cnt'],
      default: 'cnt',
      description: 'Asset archetype: "single" = one NFT, "multi" = several NFTs, "cnt" = any fungible token.',
      aiEditable: true,
    },
    privacy: {
      type: 'enum',
      step: 1,
      required: true,
      values: ['public', 'private', 'semi-private'],
      default: 'public',
      description:
        'Who may participate. "private" and "semi-private" require whitelists the user must supply manually.',
      aiEditable: true,
    },
    preset_id: {
      type: 'string',
      step: 1,
      required: true,
      description: 'Id of one of the presets listed in the conversation context. Pick the closest match.',
      aiEditable: true,
    },
    vaultTokenTicker: {
      type: 'string',
      step: 1,
      required: true,
      minLength: 1,
      maxLength: 9,
      pattern: '^[A-Za-z0-9]{1,9}$',
      description: 'Ticker of the governance (vault) token. Letters and digits only.',
      aiEditable: true,
    },
    description: {
      type: 'string',
      step: 1,
      maxLength: 500,
      description: 'Vault description shown on the vault profile page.',
      aiEditable: true,
    },
    tokenDescription: {
      type: 'string',
      step: 1,
      maxLength: 300,
      description: 'Description registered in the vault token metadata.',
      aiEditable: true,
    },
    tags: {
      type: 'enumArray',
      step: 1,
      values: VAULT_TAGS,
      description: 'Up to 5 discovery tags.',
      max: 5,
      aiEditable: true,
    },
    allowAcquireExpansion: {
      type: 'boolean',
      step: 1,
      default: false,
      description: 'Allow governance proposals that open additional acquire windows after the vault locks.',
      aiEditable: true,
    },
    isExpandableAssetWhitelist: {
      type: 'boolean',
      step: 1,
      default: false,
      description: 'Allow governance to add collections to the asset whitelist after launch.',
      aiEditable: true,
    },
    vaultImage: {
      type: 'string',
      step: 1,
      required: true,
      description: 'Vault image URL. Produced by the image endpoint — never generated by the model.',
      aiEditable: false,
    },
    ftTokenImg: {
      type: 'string',
      step: 1,
      required: true,
      description: 'Vault token image URL. Produced by the image endpoint — never generated by the model.',
      aiEditable: false,
    },
    socialLinks: {
      type: 'string',
      step: 1,
      description: 'Social links. Supplied by the user in the form — never generated by the model.',
      aiEditable: false,
    },
    contributorWhitelist: {
      type: 'string',
      step: 1,
      requiredWhen: 'privacy is "private" and valueMethod is "lbe"',
      requiredIf: [
        { field: 'privacy', equals: 'private' },
        { field: 'valueMethod', equals: 'lbe' },
      ],
      description: 'Contributor wallet addresses. Supplied by the user in the form — never generated by the model.',
      aiEditable: false,
    },
    acquirerWhitelist: {
      type: 'string',
      step: 1,
      requiredWhen: 'privacy is "private"',
      requiredIf: [{ field: 'privacy', equals: 'private' }],
      description: 'Acquirer wallet addresses. Supplied by the user in the form — never generated by the model.',
      aiEditable: false,
    },
    assetsWhitelist: {
      type: 'string',
      step: 1,
      required: true,
      requiredWhen: 'isAcquireOnly is false',
      notApplicableIf: [{ field: 'isAcquireOnly', equals: true }],
      description: 'Allowed collections. Must be picked from verified collections in the form — never generated.',
      aiEditable: false,
    },

    // --- Step 2: Contribute --------------------------------------------------
    valueMethod: {
      type: 'enum',
      step: 2,
      required: true,
      values: ['lbe', 'fixed'],
      default: 'lbe',
      description: '"lbe" = market/floor pricing, "fixed" = a fixed valuation. "fixed" requires privacy = private.',
      aiEditable: true,
    },
    valuationCurrency: {
      type: 'string',
      step: 2,
      requiredWhen: 'valueMethod is "fixed"',
      requiredIf: [
        { field: 'privacy', equals: 'private' },
        { field: 'valueMethod', equals: 'fixed' },
      ],
      description:
        'Currency of the fixed valuation. Only applies to a private vault using fixed valuation; ' +
        'leave null otherwise and never ask the user for it.',
      aiEditable: true,
    },
    valuationAmount: {
      type: 'number',
      step: 2,
      requiredWhen: 'valueMethod is "fixed"',
      requiredIf: [
        { field: 'privacy', equals: 'private' },
        { field: 'valueMethod', equals: 'fixed' },
      ],
      min: 0,
      description:
        'Amount of the fixed valuation. Only applies to a private vault using fixed valuation; ' +
        'leave null otherwise and never ask the user for it.',
      aiEditable: true,
    },
    contributionOpenWindowType: {
      type: 'enum',
      step: 2,
      required: true,
      values: ['upon-vault-launch', 'custom'],
      default: 'upon-vault-launch',
      notApplicableIf: [{ field: 'isAcquireOnly', equals: true }],
      description: 'When the asset contribution window opens.',
      aiEditable: true,
    },
    contributionOpenWindowTime: {
      type: 'number',
      step: 2,
      requiredWhen: 'contributionOpenWindowType is "custom"',
      requiredIf: [{ field: 'contributionOpenWindowType', equals: 'custom' }],
      notApplicableIf: [{ field: 'isAcquireOnly', equals: true }],
      description:
        'Unix timestamp in milliseconds for a custom contribution window opening. Only applies when the ' +
        'contribution window type is "custom"; leave null otherwise.',
      aiEditable: true,
    },
    contributionDuration: {
      type: 'integer',
      step: 2,
      required: true,
      unit: 'ms',
      min: 300_000,
      max: 30 * DAY_MS,
      notApplicableIf: [{ field: 'isAcquireOnly', equals: true }],
      description: 'How long the asset contribution window stays open. Not used when isAcquireOnly is true.',
      aiEditable: true,
    },

    // --- Step 3: Acquire -----------------------------------------------------
    acquireOpenWindowType: {
      type: 'enum',
      step: 3,
      required: true,
      values: ['upon-asset-window-closing', 'custom'],
      default: 'upon-asset-window-closing',
      notApplicableIf: [{ field: 'tokensForAcquires', equals: 0 }],
      description: 'When the acquire window opens.',
      aiEditable: true,
    },
    acquireOpenWindowTime: {
      type: 'number',
      step: 3,
      requiredWhen: 'acquireOpenWindowType is "custom"',
      requiredIf: [{ field: 'acquireOpenWindowType', equals: 'custom' }],
      notApplicableIf: [{ field: 'tokensForAcquires', equals: 0 }],
      description:
        'Unix timestamp in milliseconds for a custom acquire window opening. Only applies when the acquire ' +
        'window type is "custom"; leave null otherwise.',
      aiEditable: true,
    },
    acquireWindowDuration: {
      type: 'integer',
      step: 3,
      required: true,
      unit: 'ms',
      min: 300_000,
      max: 30 * DAY_MS,
      notApplicableIf: [{ field: 'tokensForAcquires', equals: 0 }],
      description: 'How long the acquire window stays open. Not used when tokensForAcquires is 0.',
      aiEditable: true,
    },
    tokensForAcquires: {
      type: 'number',
      step: 3,
      required: true,
      unit: '%',
      min: 0,
      max: 100,
      description: 'Share of net vault tokens distributed to acquirers when the vault locks.',
      aiEditable: true,
    },
    acquireReserve: {
      type: 'number',
      step: 3,
      required: true,
      unit: '%',
      min: 0,
      max: 100,
      description: 'Share of the acquire allocation held back as reserve.',
      aiEditable: true,
    },
    liquidityPoolContribution: {
      type: 'number',
      step: 3,
      required: true,
      unit: '%',
      min: 0,
      max: 100,
      description: 'Share of vault tokens seeded into the liquidity pool. Must be 0 when tokensForAcquires is 0.',
      aiEditable: true,
    },
    isAcquireOnly: {
      type: 'boolean',
      step: 3,
      default: false,
      description: 'Acquire-only vault: no asset contribution window, tokensForAcquires is forced to 100.',
      aiEditable: true,
    },
    minAcquireThreshold: {
      type: 'number',
      step: 3,
      unit: 'ADA',
      min: 1,
      description:
        'Optional floor the acquire window must reach for the vault to lock. Only used when isAcquireOnly is true.',
      aiEditable: true,
    },

    // --- Step 4: Govern ------------------------------------------------------
    ftTokenSupply: {
      type: 'integer',
      step: 4,
      required: true,
      min: 1_000_000,
      max: 1_000_000_000_000,
      default: 1_000_000,
      unit: 'vault tokens',
      description: 'Total supply of the vault (governance) token, denominated in vault tokens.',
      aiEditable: true,
    },
    terminationType: {
      type: 'enum',
      step: 4,
      required: true,
      values: ['dao'],
      default: 'dao',
      description: 'How the vault can be terminated.',
      aiEditable: true,
    },
    creationThreshold: {
      type: 'number',
      step: 4,
      required: true,
      unit: '%',
      min: 0.5,
      max: 100,
      description: 'Minimum share of vault tokens a holder needs to open a governance proposal.',
      aiEditable: true,
    },
    cosigningThreshold: {
      type: 'number',
      step: 4,
      required: true,
      unit: '%',
      min: 33,
      max: 100,
      description: 'Participation quorum a proposal must reach to be valid.',
      aiEditable: true,
    },
    executionThreshold: {
      type: 'number',
      step: 4,
      required: true,
      unit: '%',
      min: 50.1,
      max: 100,
      description: 'Share of yes votes required for a proposal to pass.',
      aiEditable: true,
    },
    voteThreshold: {
      type: 'number',
      step: 4,
      default: 0,
      description: 'Reserved, always 0.',
      aiEditable: false,
    },
  },

  networkOverrides: {
    preprod: {
      contributionDuration: { min: 300_000, default: 7 * DAY_MS },
      acquireWindowDuration: { min: 300_000, default: 7 * DAY_MS },
    },
    mainnet: {
      contributionDuration: { min: 5 * DAY_MS, default: 7 * DAY_MS },
      acquireWindowDuration: { min: 5 * DAY_MS, default: 7 * DAY_MS },
    },
  },

  chainProfiles: {
    [ChainType.cardano]: {
      currency: 'ADA',
      assetIdentifier: '56-character hex policy ID',
      rules: ['minAcquireThreshold is entered in whole ADA and must be an integer.'],
    },
    [ChainType.robinhood]: {
      currency: 'ETH',
      assetIdentifier: '0x-prefixed 40-character contract address',
      fields: {
        privacy: {
          values: ['public'],
          description: 'Robinhood Chain vaults are always public.',
        },
        minAcquireThreshold: { unit: 'ETH', min: 0.01, max: 10_000 },
      },
      rules: [
        'Robinhood Chain vaults are always public — never propose "private" or "semi-private".',
        'minAcquireThreshold is entered in ETH and may be fractional.',
      ],
    },
  },
};
